name: ProjectEU_Dart
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: vykend.github.io/Dictionary
#author: Martin Výlet

environment:
  sdk: '>=1.24.1 <2.0.0'

dependencies:
  angular2: ^3.0.0
  angular_components: ^0.5.1
  queries: ^0.0.15

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular2:
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
